[2024-10-24T01:26:56.920+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-27T08:00:00+00:00 [queued]>
[2024-10-24T01:26:56.940+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-27T08:00:00+00:00 [queued]>
[2024-10-24T01:26:56.941+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:26:57.034+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-27 08:00:00+00:00
[2024-10-24T01:26:57.044+0000] {standard_task_runner.py:57} INFO - Started process 8817 to run task
[2024-10-24T01:26:57.054+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-27T08:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpf836xkj7']
[2024-10-24T01:26:57.065+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask Silver
[2024-10-24T01:26:57.206+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-27T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:26:57.543+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-27T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-27T08:00:00+00:00'
[2024-10-24T01:26:57.583+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:26:57.588+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:27:28.435+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T01:27:28.441+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T01:27:28.443+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 INFO SparkContext: Java version 11.0.25
[2024-10-24T01:27:28.921+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T01:27:29.915+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:29.917+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T01:27:29.921+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:29.923+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T01:27:30.078+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T01:27:30.182+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T01:27:30.184+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T01:27:30.806+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T01:27:30.811+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T01:27:30.824+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T01:27:30.826+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T01:27:30.828+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T01:27:33.554+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO Utils: Successfully started service 'sparkDriver' on port 39629.
[2024-10-24T01:27:33.983+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T01:27:34.513+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T01:27:34.847+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T01:27:34.849+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T01:27:34.912+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T01:27:34.995+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b0bf8398-462f-4f0a-b6c7-642c72db2390
[2024-10-24T01:27:35.048+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T01:27:35.205+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T01:27:37.085+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T01:27:37.831+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-10-24T01:27:37.850+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-10-24T01:27:37.953+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2024-10-24T01:27:39.928+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:27:40.797+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO TransportClientFactory: Successfully created connection to spark-master/172.22.0.3:7077 after 529 ms (0 ms spent in bootstraps)
[2024-10-24T01:27:41.836+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024012741-0045
[2024-10-24T01:27:41.864+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46171.
[2024-10-24T01:27:41.866+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO NettyBlockTransferService: Server created on de5108c6da1d:46171
[2024-10-24T01:27:41.867+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T01:27:41.888+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, de5108c6da1d, 46171, None)
[2024-10-24T01:27:41.904+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO BlockManagerMasterEndpoint: Registering block manager de5108c6da1d:46171 with 434.4 MiB RAM, BlockManagerId(driver, de5108c6da1d, 46171, None)
[2024-10-24T01:27:41.916+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, de5108c6da1d, 46171, None)
[2024-10-24T01:27:41.917+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, de5108c6da1d, 46171, None)
[2024-10-24T01:29:33.867+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:33 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener HeartbeatReceiver took 1.906332987s.
[2024-10-24T01:29:35.364+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:35 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener AppStatusListener took 3.732284757s.
[2024-10-24T01:30:07.421+0000] {spark_submit.py:524} INFO - 24/10/24 01:30:07 INFO AsyncEventQueue: Process of event SparkListenerBlockManagerAdded(1729733261893,BlockManagerId(driver, de5108c6da1d, 46171, None),455501414,Some(455501414),Some(0)) by listener AppStatusListener took 29.696672662s.
[2024-10-24T01:30:53.748+0000] {spark_submit.py:524} INFO - 24/10/24 01:30:53 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@770aefa7)) by listener AppStatusListener took 46.013475677s.
[2024-10-24T01:32:13.265+0000] {spark_submit.py:524} INFO - 24/10/24 01:32:09 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@51bfadc5)) by listener AppStatusListener took 8.586301192s.
[2024-10-24T01:32:45.978+0000] {spark_submit.py:524} INFO - 24/10/24 01:32:25 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@49f0bbbf)) by listener AppStatusListener took 2.07854121s.
[2024-10-24T01:33:24.878+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:23 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@7aff3959)) by listener AppStatusListener took 4.424757873s.
[2024-10-24T01:33:43.752+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:42 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@4c6e5f28)) by listener AppStatusListener took 1.723647157s.
[2024-10-24T01:32:12.949+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:34:00.615+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:00 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T01:35:25.787+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024012741-0045/0 on worker-20241024010948-172.22.0.4-41535 (172.22.0.4:41535) with 2 core(s)
[2024-10-24T01:35:25.794+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024012741-0045/0 on hostPort 172.22.0.4:41535 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T01:35:25.795+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T01:35:25.798+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T01:35:25.918+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024012741-0045/0 is now RUNNING
[2024-10-24T01:35:25.937+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO SparkUI: Stopped Spark web UI at http://de5108c6da1d:4042
[2024-10-24T01:35:25.963+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T01:35:25.981+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T01:35:26.062+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T01:35:26.178+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:26 INFO MemoryStore: MemoryStore cleared
[2024-10-24T01:35:26.182+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:26 INFO BlockManager: BlockManager stopped
[2024-10-24T01:35:26.207+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:26 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T01:35:26.212+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T01:35:26.279+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-10-24T01:35:26.285+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:26 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T01:35:26.296+0000] {process_utils.py:131} INFO - Sending 15 to group 8817. PIDs of all processes in the group: [8822, 9518, 8817]
[2024-10-24T01:35:26.302+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 8817
[2024-10-24T01:35:26.304+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:35:26.306+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:35:26.352+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:35:26.375+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231127T080000, start_date=20241024T012656, end_date=20241024T013526
[2024-10-24T01:35:26.406+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task Silver (Task received SIGTERM signal; 8817)
[2024-10-24T01:35:26.442+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8817, status='terminated', exitcode=1, started='01:26:56') (8817) terminated with exit code 1
[2024-10-24T01:35:26.444+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9518, status='terminated', started='01:27:16') (9518) terminated with exit code None
[2024-10-24T01:35:26.445+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8822, status='terminated', started='01:26:57') (8822) terminated with exit code None
