[2024-10-24T01:26:57.563+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-30T08:00:00+00:00 [queued]>
[2024-10-24T01:26:57.583+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-30T08:00:00+00:00 [queued]>
[2024-10-24T01:26:57.583+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:26:57.801+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-30 08:00:00+00:00
[2024-10-24T01:26:57.815+0000] {standard_task_runner.py:57} INFO - Started process 8827 to run task
[2024-10-24T01:26:57.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-30T08:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmp3aka5c28']
[2024-10-24T01:26:57.870+0000] {standard_task_runner.py:85} INFO - Job 139: Subtask Silver
[2024-10-24T01:26:58.041+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-30T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:26:58.380+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T08:00:00+00:00'
[2024-10-24T01:26:58.434+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:26:58.439+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:27:28.461+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T01:27:28.487+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T01:27:28.488+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:28 INFO SparkContext: Java version 11.0.25
[2024-10-24T01:27:29.139+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T01:27:30.115+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:30.117+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T01:27:30.119+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:30.120+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T01:27:30.371+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T01:27:30.497+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T01:27:30.515+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T01:27:30.874+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T01:27:30.877+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T01:27:30.880+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T01:27:30.882+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T01:27:30.886+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T01:27:33.292+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO Utils: Successfully started service 'sparkDriver' on port 46283.
[2024-10-24T01:27:33.546+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T01:27:33.902+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T01:27:34.082+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T01:27:34.085+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T01:27:34.099+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T01:27:34.406+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-65cf6178-61ae-431e-b08b-ef34f0f114b6
[2024-10-24T01:27:34.622+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T01:27:34.793+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T01:27:36.669+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:36 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T01:27:37.332+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-10-24T01:27:37.487+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2024-10-24T01:27:38.876+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:27:39.312+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO TransportClientFactory: Successfully created connection to spark-master/172.22.0.3:7077 after 224 ms (0 ms spent in bootstraps)
[2024-10-24T01:27:40.448+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024012740-0043
[2024-10-24T01:27:40.571+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41629.
[2024-10-24T01:27:40.571+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO NettyBlockTransferService: Server created on de5108c6da1d:41629
[2024-10-24T01:27:40.574+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T01:27:40.665+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, de5108c6da1d, 41629, None)
[2024-10-24T01:27:40.694+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMasterEndpoint: Registering block manager de5108c6da1d:41629 with 434.4 MiB RAM, BlockManagerId(driver, de5108c6da1d, 41629, None)
[2024-10-24T01:27:40.708+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, de5108c6da1d, 41629, None)
[2024-10-24T01:27:40.712+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, de5108c6da1d, 41629, None)
[2024-10-24T01:27:57.357+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:56 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener HeartbeatReceiver took 1.559644251s.
[2024-10-24T01:28:04.249+0000] {spark_submit.py:524} INFO - 24/10/24 01:28:03 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener AppStatusListener took 8.71149332s.
[2024-10-24T01:28:59.176+0000] {spark_submit.py:524} INFO - 24/10/24 01:28:59 INFO AsyncEventQueue: Process of event SparkListenerBlockManagerAdded(1729733260691,BlockManagerId(driver, de5108c6da1d, 41629, None),455501414,Some(455501414),Some(0)) by listener AppStatusListener took 53.789105362s.
[2024-10-24T01:29:01.321+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:01 INFO AsyncEventQueue: Process of event SparkListenerApplicationStart(IngestaoSilver,Some(app-20241024012740-0043),1729733248389,***,None,None,None) by listener AppStatusListener took 1.127573273s.
[2024-10-24T01:29:21.044+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:21 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@65fe9141)) by listener AppStatusListener took 15.158160565s.
[2024-10-24T01:29:31.454+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:31 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T01:30:52.326+0000] {spark_submit.py:524} INFO - 24/10/24 01:30:52 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@2bd1144d)) by listener AppStatusListener took 12.708842689s.
[2024-10-24T01:32:12.149+0000] {spark_submit.py:524} INFO - 24/10/24 01:32:08 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@3a34ecef)) by listener AppStatusListener took 1.353639427s.
[2024-10-24T01:32:42.187+0000] {spark_submit.py:524} INFO - 24/10/24 01:32:40 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@4a104528)) by listener AppStatusListener took 1.766687829s.
[2024-10-24T01:31:50.823+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 215, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/local_task_job_runner.py", line 246, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 864, in refresh_from_db
    ti = qry.one_or_none()
         ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:33:22.357+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:20 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@3c7441ea)) by listener AppStatusListener took 1.168046868s.
[2024-10-24T01:33:39.976+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:39 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@1f245955)) by listener AppStatusListener took 8.330711839s.
[2024-10-24T01:33:38.044+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:34:02.501+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:02 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024012740-0043/0 on worker-20241024010948-172.22.0.4-41535 (172.22.0.4:41535) with 2 core(s)
[2024-10-24T01:34:02.520+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:02 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024012740-0043/0 on hostPort 172.22.0.4:41535 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T01:34:02.762+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:02 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024012740-0043/0 is now RUNNING
[2024-10-24T01:34:03.719+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T01:34:03.760+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:03 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T01:34:04.116+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:04 INFO SparkUI: Stopped Spark web UI at http://de5108c6da1d:4041
[2024-10-24T01:34:11.281+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:10 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T01:34:30.886+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:30 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T01:35:24.599+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-10-24T01:35:24.842+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T01:35:24.846+0000] {process_utils.py:131} INFO - Sending 15 to group 8827. PIDs of all processes in the group: [8861, 9575, 8827]
[2024-10-24T01:35:24.866+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 8827
[2024-10-24T01:35:24.871+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:35:24.874+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:35:25.172+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9575, status='terminated', started='01:27:19') (9575) terminated with exit code None
[2024-10-24T01:35:25.192+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:35:25.281+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231130T080000, start_date=20241024T012657, end_date=20241024T013525
[2024-10-24T01:35:25.429+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 139 for task Silver (Task received SIGTERM signal; 8827)
[2024-10-24T01:35:25.505+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8861, status='terminated', started='01:26:57') (8861) terminated with exit code None
[2024-10-24T01:35:25.508+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8827, status='terminated', exitcode=1, started='01:26:57') (8827) terminated with exit code 1
[2024-10-24T14:35:06.475+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:35:06.483+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:35:06.516+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:35:06.516+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:35:06.546+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-30T08:00:00+00:00 [queued]>
[2024-10-24T14:35:06.552+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-30T08:00:00+00:00 [queued]>
[2024-10-24T14:35:06.553+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-24T14:35:06.563+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-30 08:00:00+00:00
[2024-10-24T14:35:06.567+0000] {standard_task_runner.py:57} INFO - Started process 12976 to run task
[2024-10-24T14:35:06.569+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-30T08:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpz7ebr5ut']
[2024-10-24T14:35:06.570+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask Silver
[2024-10-24T14:35:06.616+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:35:06.616+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-30T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:35:06.617+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-30T08:00:00+00:00 [running]> on host 96f89615839b
[2024-10-24T14:35:06.696+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T08:00:00+00:00'
[2024-10-24T14:35:06.707+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T14:35:06.708+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/silver/api_openbrewerydb.py
[2024-10-24T14:35:09.433+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T14:35:09.435+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T14:35:09.435+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkContext: Java version 11.0.25
[2024-10-24T14:35:09.493+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T14:35:09.578+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO ResourceUtils: ==============================================================
[2024-10-24T14:35:09.578+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T14:35:09.579+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO ResourceUtils: ==============================================================
[2024-10-24T14:35:09.579+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T14:35:09.601+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T14:35:09.614+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T14:35:09.615+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T14:35:09.661+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T14:35:09.662+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T14:35:09.662+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T14:35:09.663+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T14:35:09.663+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T14:35:09.892+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO Utils: Successfully started service 'sparkDriver' on port 43753.
[2024-10-24T14:35:09.916+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T14:35:09.945+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T14:35:09.964+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T14:35:09.964+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T14:35:09.967+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T14:35:09.985+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-ae9afd6f-a113-4f71-af2b-e26a4dbdd056
[2024-10-24T14:35:09.998+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:09 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T14:35:10.011+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T14:35:10.153+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T14:35:10.204+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-24T14:35:10.314+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T14:35:10.363+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 29 ms (0 ms spent in bootstraps)
[2024-10-24T14:35:10.444+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024143510-0080
[2024-10-24T14:35:10.446+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024143510-0080/0 on worker-20241024142308-172.18.0.5-43899 (172.18.0.5:43899) with 2 core(s)
[2024-10-24T14:35:10.449+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024143510-0080/0 on hostPort 172.18.0.5:43899 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T14:35:10.454+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42917.
[2024-10-24T14:35:10.455+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO NettyBlockTransferService: Server created on 96f89615839b:42917
[2024-10-24T14:35:10.457+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T14:35:10.470+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 96f89615839b, 42917, None)
[2024-10-24T14:35:10.474+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024143510-0080/0 is now RUNNING
[2024-10-24T14:35:10.476+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO BlockManagerMasterEndpoint: Registering block manager 96f89615839b:42917 with 434.4 MiB RAM, BlockManagerId(driver, 96f89615839b, 42917, None)
[2024-10-24T14:35:10.479+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 96f89615839b, 42917, None)
[2024-10-24T14:35:10.481+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 96f89615839b, 42917, None)
[2024-10-24T14:35:10.776+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:10 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T14:35:11.018+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T14:35:11.019+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T14:35:11.031+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO SparkUI: Stopped Spark web UI at http://96f89615839b:4040
[2024-10-24T14:35:11.036+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T14:35:11.041+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T14:35:11.059+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T14:35:11.068+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO MemoryStore: MemoryStore cleared
[2024-10-24T14:35:11.069+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO BlockManager: BlockManager stopped
[2024-10-24T14:35:11.076+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T14:35:11.078+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T14:35:11.085+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T14:35:11.354+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO ShutdownHookManager: Shutdown hook called
[2024-10-24T14:35:11.354+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-f3b163ea-fe20-4b26-a23c-8054ad6cda69
[2024-10-24T14:35:11.357+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-3a36a759-7c4a-4a8e-b03c-267d641f6da6/pyspark-3f5a2d8d-e01c-43a1-b85c-4cc5cae0088c
[2024-10-24T14:35:11.360+0000] {spark_submit.py:524} INFO - 24/10/24 14:35:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-3a36a759-7c4a-4a8e-b03c-267d641f6da6
[2024-10-24T14:35:11.402+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231130T080000, start_date=20241024T143506, end_date=20241024T143511
[2024-10-24T14:35:11.434+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-24T14:35:11.476+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
